export default[
  {
    short_name: 'AD',
    long_name: 'Andorra',
  }, {
    short_name: 'AE',
    long_name: 'United Arab Emirates',
  }, {
    short_name: 'AF',
    long_name: 'Afghanistan',
  }, {
    short_name: 'AG',
    long_name: 'Antigua and Barbuda',
  }, {
    short_name: 'AI',
    long_name: 'Anguilla',
  }, {
    short_name: 'AL',
    long_name: 'Albania',
  }, {
    short_name: 'AM',
    long_name: 'Armenia',
  }, {
    short_name: 'AO',
    long_name: 'Angola',
  }, {
    short_name: 'AQ',
    long_name: 'Antarctica',
  }, {
    short_name: 'AR',
    long_name: 'Argentina',
  }, {
    short_name: 'AS',
    long_name: 'American Samoa',
  }, {
    short_name: 'AT',
    long_name: 'Austria',
  }, {
    short_name: 'AU',
    long_name: 'Australia',
  }, {
    short_name: 'AW',
    long_name: 'Aruba',
  }, {
    short_name: 'AX',
    long_name: 'Aland Islands',
  }, {
    short_name: 'AZ',
    long_name: 'Azerbaijan',
  }, {
    short_name: 'BA',
    long_name: 'Bosnia and Herzegovina',
  }, {
    short_name: 'BB',
    long_name: 'Barbados',
  }, {
    short_name: 'BD',
    long_name: 'Bangladesh',
  }, {
    short_name: 'BE',
    long_name: 'Belgium',
  }, {
    short_name: 'BF',
    long_name: 'Burkina Faso',
  }, {
    short_name: 'BG',
    long_name: 'Bulgaria',
  }, {
    short_name: 'BH',
    long_name: 'Bahrain',
  }, {
    short_name: 'BI',
    long_name: 'Burundi',
  }, {
    short_name: 'BJ',
    long_name: 'Benin',
  }, {
    short_name: 'BL',
    long_name: 'Saint Barthelemy',
  }, {
    short_name: 'BM',
    long_name: 'Bermuda',
  }, {
    short_name: 'BN',
    long_name: 'Brunei',
  }, {
    short_name: 'BO',
    long_name: 'Bolivia',
  }, {
    short_name: 'BQ',
    long_name: 'Bonaire, Saint Eustatius and Saba ',
  }, {
    short_name: 'BR',
    long_name: 'Brazil',
  }, {
    short_name: 'BS',
    long_name: 'Bahamas',
  }, {
    short_name: 'BT',
    long_name: 'Bhutan',
  }, {
    short_name: 'BV',
    long_name: 'Bouvet Island',
  }, {
    short_name: 'BW',
    long_name: 'Botswana',
  }, {
    short_name: 'BY',
    long_name: 'Belarus',
  }, {
    short_name: 'BZ',
    long_name: 'Belize',
  }, {
    short_name: 'CA',
    long_name: 'Canada',
  }, {
    short_name: 'CC',
    long_name: 'Cocos Islands',
  }, {
    short_name: 'CD',
    long_name: 'Democratic Republic of the Congo',
  }, {
    short_name: 'CF',
    long_name: 'Central African Republic',
  }, {
    short_name: 'CG',
    long_name: 'Republic of the Congo',
  }, {
    short_name: 'CH',
    long_name: 'Switzerland',
  }, {
    short_name: 'CI',
    long_name: 'Ivory Coast',
  }, {
    short_name: 'CK',
    long_name: 'Cook Islands',
  }, {
    short_name: 'CL',
    long_name: 'Chile',
  }, {
    short_name: 'CM',
    long_name: 'Cameroon',
  }, {
    short_name: 'CN',
    long_name: 'China',
  }, {
    short_name: 'CO',
    long_name: 'Colombia',
  }, {
    short_name: 'CR',
    long_name: 'Costa Rica',
  }, {
    short_name: 'CU',
    long_name: 'Cuba',
  }, {
    short_name: 'CV',
    long_name: 'Cape Verde',
  }, {
    short_name: 'CW',
    long_name: 'Curacao',
  }, {
    short_name: 'CX',
    long_name: 'Christmas Island',
  }, {
    short_name: 'CY',
    long_name: 'Cyprus',
  }, {
    short_name: 'CZ',
    long_name: 'Czechia',
  }, {
    short_name: 'DE',
    long_name: 'Germany',
  }, {
    short_name: 'DJ',
    long_name: 'Djibouti',
  }, {
    short_name: 'DK',
    long_name: 'Denmark',
  }, {
    short_name: 'DM',
    long_name: 'Dominica',
  }, {
    short_name: 'DO',
    long_name: 'Dominican Republic',
  }, {
    short_name: 'DZ',
    long_name: 'Algeria',
  }, {
    short_name: 'EC',
    long_name: 'Ecuador',
  }, {
    short_name: 'EE',
    long_name: 'Estonia',
  }, {
    short_name: 'EG',
    long_name: 'Egypt',
  }, {
    short_name: 'EH',
    long_name: 'Western Sahara',
  }, {
    short_name: 'ER',
    long_name: 'Eritrea',
  }, {
    short_name: 'ES',
    long_name: 'Spain',
  }, {
    short_name: 'ET',
    long_name: 'Ethiopia',
  }, {
    short_name: 'FI',
    long_name: 'Finland',
  }, {
    short_name: 'FJ',
    long_name: 'Fiji',
  }, {
    short_name: 'FK',
    long_name: 'Falkland Islands',
  }, {
    short_name: 'FM',
    long_name: 'Micronesia',
  }, {
    short_name: 'FO',
    long_name: 'Faroe Islands',
  }, {
    short_name: 'FR',
    long_name: 'France',
  }, {
    short_name: 'GA',
    long_name: 'Gabon',
  }, {
    short_name: 'GB',
    long_name: 'United Kingdom',
  }, {
    short_name: 'GD',
    long_name: 'Grenada',
  }, {
    short_name: 'GE',
    long_name: 'Georgia',
  }, {
    short_name: 'GF',
    long_name: 'French Guiana',
  }, {
    short_name: 'GG',
    long_name: 'Guernsey',
  }, {
    short_name: 'GH',
    long_name: 'Ghana',
  }, {
    short_name: 'GI',
    long_name: 'Gibraltar',
  }, {
    short_name: 'GL',
    long_name: 'Greenland',
  }, {
    short_name: 'GM',
    long_name: 'Gambia',
  }, {
    short_name: 'GN',
    long_name: 'Guinea',
  }, {
    short_name: 'GP',
    long_name: 'Guadeloupe',
  }, {
    short_name: 'GQ',
    long_name: 'Equatorial Guinea',
  }, {
    short_name: 'GR',
    long_name: 'Greece',
  }, {
    short_name: 'GS',
    long_name: 'South Georgia and the South Sandwich Islands',
  }, {
    short_name: 'GT',
    long_name: 'Guatemala',
  }, {
    short_name: 'GU',
    long_name: 'Guam',
  }, {
    short_name: 'GW',
    long_name: 'Guinea-Bissau',
  }, {
    short_name: 'GY',
    long_name: 'Guyana',
  }, {
    short_name: 'HK',
    long_name: 'Hong Kong',
  }, {
    short_name: 'HM',
    long_name: 'Heard Island and McDonald Islands',
  }, {
    short_name: 'HN',
    long_name: 'Honduras',
  }, {
    short_name: 'HR',
    long_name: 'Croatia',
  }, {
    short_name: 'HT',
    long_name: 'Haiti',
  }, {
    short_name: 'HU',
    long_name: 'Hungary',
  }, {
    short_name: 'ID',
    long_name: 'Indonesia',
  }, {
    short_name: 'IE',
    long_name: 'Ireland',
  }, {
    short_name: 'IL',
    long_name: 'Israel',
  }, {
    short_name: 'IM',
    long_name: 'Isle of Man',
  }, {
    short_name: 'IN',
    long_name: 'India',
  }, {
    short_name: 'IO',
    long_name: 'British Indian Ocean Territory',
  }, {
    short_name: 'IQ',
    long_name: 'Iraq',
  }, {
    short_name: 'IR',
    long_name: 'Iran',
  }, {
    short_name: 'IS',
    long_name: 'Iceland',
  }, {
    short_name: 'IT',
    long_name: 'Italy',
  }, {
    short_name: 'JE',
    long_name: 'Jersey',
  }, {
    short_name: 'JM',
    long_name: 'Jamaica',
  }, {
    short_name: 'JO',
    long_name: 'Jordan',
  }, {
    short_name: 'JP',
    long_name: 'Japan',
  }, {
    short_name: 'KE',
    long_name: 'Kenya',
  }, {
    short_name: 'KG',
    long_name: 'Kyrgyzstan',
  }, {
    short_name: 'KH',
    long_name: 'Cambodia',
  }, {
    short_name: 'KI',
    long_name: 'Kiribati',
  }, {
    short_name: 'KM',
    long_name: 'Comoros',
  }, {
    short_name: 'KN',
    long_name: 'Saint Kitts and Nevis',
  }, {
    short_name: 'KP',
    long_name: 'North Korea',
  }, {
    short_name: 'KR',
    long_name: 'South Korea',
  }, {
    short_name: 'XK',
    long_name: 'Kosovo',
  }, {
    short_name: 'KW',
    long_name: 'Kuwait',
  }, {
    short_name: 'KY',
    long_name: 'Cayman Islands',
  }, {
    short_name: 'KZ',
    long_name: 'Kazakhstan',
  }, {
    short_name: 'LA',
    long_name: 'Laos',
  }, {
    short_name: 'LB',
    long_name: 'Lebanon',
  }, {
    short_name: 'LC',
    long_name: 'Saint Lucia',
  }, {
    short_name: 'LI',
    long_name: 'Liechtenstein',
  }, {
    short_name: 'LK',
    long_name: 'Sri Lanka',
  }, {
    short_name: 'LR',
    long_name: 'Liberia',
  }, {
    short_name: 'LS',
    long_name: 'Lesotho',
  }, {
    short_name: 'LT',
    long_name: 'Lithuania',
  }, {
    short_name: 'LU',
    long_name: 'Luxembourg',
  }, {
    short_name: 'LV',
    long_name: 'Latvia',
  }, {
    short_name: 'LY',
    long_name: 'Libya',
  }, {
    short_name: 'MA',
    long_name: 'Morocco',
  }, {
    short_name: 'MC',
    long_name: 'Monaco',
  }, {
    short_name: 'MD',
    long_name: 'Moldova',
  }, {
    short_name: 'ME',
    long_name: 'Montenegro',
  }, {
    short_name: 'MF',
    long_name: 'Saint Martin',
  }, {
    short_name: 'MG',
    long_name: 'Madagascar',
  }, {
    short_name: 'MH',
    long_name: 'Marshall Islands',
  }, {
    short_name: 'MK',
    long_name: 'Macedonia',
  }, {
    short_name: 'ML',
    long_name: 'Mali',
  }, {
    short_name: 'MM',
    long_name: 'Myanmar',
  }, {
    short_name: 'MN',
    long_name: 'Mongolia',
  }, {
    short_name: 'MO',
    long_name: 'Macao',
  }, {
    short_name: 'MP',
    long_name: 'Northern Mariana Islands',
  }, {
    short_name: 'MQ',
    long_name: 'Martinique',
  }, {
    short_name: 'MR',
    long_name: 'Mauritania',
  }, {
    short_name: 'MS',
    long_name: 'Montserrat',
  }, {
    short_name: 'MT',
    long_name: 'Malta',
  }, {
    short_name: 'MU',
    long_name: 'Mauritius',
  }, {
    short_name: 'MV',
    long_name: 'Maldives',
  }, {
    short_name: 'MW',
    long_name: 'Malawi',
  }, {
    short_name: 'MX',
    long_name: 'Mexico',
  }, {
    short_name: 'MY',
    long_name: 'Malaysia',
  }, {
    short_name: 'MZ',
    long_name: 'Mozambique',
  }, {
    short_name: 'NA',
    long_name: 'Namibia',
  }, {
    short_name: 'NC',
    long_name: 'New Caledonia',
  }, {
    short_name: 'NE',
    long_name: 'Niger',
  }, {
    short_name: 'NF',
    long_name: 'Norfolk Island',
  }, {
    short_name: 'NG',
    long_name: 'Nigeria',
  }, {
    short_name: 'NI',
    long_name: 'Nicaragua',
  }, {
    short_name: 'NL',
    long_name: 'Netherlands',
  }, {
    short_name: 'NO',
    long_name: 'Norway',
  }, {
    short_name: 'NP',
    long_name: 'Nepal',
  }, {
    short_name: 'NR',
    long_name: 'Nauru',
  }, {
    short_name: 'NU',
    long_name: 'Niue',
  }, {
    short_name: 'NZ',
    long_name: 'New Zealand',
  }, {
    short_name: 'OM',
    long_name: 'Oman',
  }, {
    short_name: 'PA',
    long_name: 'Panama',
  }, {
    short_name: 'PE',
    long_name: 'Peru',
  }, {
    short_name: 'PF',
    long_name: 'French Polynesia',
  }, {
    short_name: 'PG',
    long_name: 'Papua New Guinea',
  }, {
    short_name: 'PH',
    long_name: 'Philippines',
  }, {
    short_name: 'PK',
    long_name: 'Pakistan',
  }, {
    short_name: 'PL',
    long_name: 'Poland',
  }, {
    short_name: 'PM',
    long_name: 'Saint Pierre and Miquelon',
  }, {
    short_name: 'PN',
    long_name: 'Pitcairn',
  }, {
    short_name: 'PR',
    long_name: 'Puerto Rico',
  }, {
    short_name: 'PS',
    long_name: 'Palestinian Territory',
  }, {
    short_name: 'PT',
    long_name: 'Portugal',
  }, {
    short_name: 'PW',
    long_name: 'Palau',
  }, {
    short_name: 'PY',
    long_name: 'Paraguay',
  }, {
    short_name: 'QA',
    long_name: 'Qatar',
  }, {
    short_name: 'RE',
    long_name: 'Reunion',
  }, {
    short_name: 'RO',
    long_name: 'Romania',
  }, {
    short_name: 'RS',
    long_name: 'Serbia',
  }, {
    short_name: 'RU',
    long_name: 'Russia',
  }, {
    short_name: 'RW',
    long_name: 'Rwanda',
  }, {
    short_name: 'SA',
    long_name: 'Saudi Arabia',
  }, {
    short_name: 'SB',
    long_name: 'Solomon Islands',
  }, {
    short_name: 'SC',
    long_name: 'Seychelles',
  }, {
    short_name: 'SD',
    long_name: 'Sudan',
  }, {
    short_name: 'SS',
    long_name: 'South Sudan',
  }, {
    short_name: 'SE',
    long_name: 'Sweden',
  }, {
    short_name: 'SG',
    long_name: 'Singapore',
  }, {
    short_name: 'SH',
    long_name: 'Saint Helena',
  }, {
    short_name: 'SI',
    long_name: 'Slovenia',
  }, {
    short_name: 'SJ',
    long_name: 'Svalbard and Jan Mayen',
  }, {
    short_name: 'SK',
    long_name: 'Slovakia',
  }, {
    short_name: 'SL',
    long_name: 'Sierra Leone',
  }, {
    short_name: 'SM',
    long_name: 'San Marino',
  }, {
    short_name: 'SN',
    long_name: 'Senegal',
  }, {
    short_name: 'SO',
    long_name: 'Somalia',
  }, {
    short_name: 'SR',
    long_name: 'Suriname',
  }, {
    short_name: 'ST',
    long_name: 'Sao Tome and Principe',
  }, {
    short_name: 'SV',
    long_name: 'El Salvador',
  }, {
    short_name: 'SX',
    long_name: 'Sint Maarten',
  }, {
    short_name: 'SY',
    long_name: 'Syria',
  }, {
    short_name: 'SZ',
    long_name: 'Swaziland',
  }, {
    short_name: 'TC',
    long_name: 'Turks and Caicos Islands',
  }, {
    short_name: 'TD',
    long_name: 'Chad',
  }, {
    short_name: 'TF',
    long_name: 'French Southern Territories',
  }, {
    short_name: 'TG',
    long_name: 'Togo',
  }, {
    short_name: 'TH',
    long_name: 'Thailand',
  }, {
    short_name: 'TJ',
    long_name: 'Tajikistan',
  }, {
    short_name: 'TK',
    long_name: 'Tokelau',
  }, {
    short_name: 'TL',
    long_name: 'East Timor',
  }, {
    short_name: 'TM',
    long_name: 'Turkmenistan',
  }, {
    short_name: 'TN',
    long_name: 'Tunisia',
  }, {
    short_name: 'TO',
    long_name: 'Tonga',
  }, {
    short_name: 'TR',
    long_name: 'Turkey',
  }, {
    short_name: 'TT',
    long_name: 'Trinidad and Tobago',
  }, {
    short_name: 'TV',
    long_name: 'Tuvalu',
  }, {
    short_name: 'TW',
    long_name: 'Taiwan',
  }, {
    short_name: 'TZ',
    long_name: 'Tanzania',
  }, {
    short_name: 'UA',
    long_name: 'Ukraine',
  }, {
    short_name: 'UG',
    long_name: 'Uganda',
  }, {
    short_name: 'UM',
    long_name: 'United States Minor Outlying Islands',
  }, {
    short_name: 'US',
    long_name: 'United States',
  }, {
    short_name: 'UY',
    long_name: 'Uruguay',
  }, {
    short_name: 'UZ',
    long_name: 'Uzbekistan',
  }, {
    short_name: 'VA',
    long_name: 'Vatican',
  }, {
    short_name: 'VC',
    long_name: 'Saint Vincent and the Grenadines',
  }, {
    short_name: 'VE',
    long_name: 'Venezuela',
  }, {
    short_name: 'VG',
    long_name: 'British Virgin Islands',
  }, {
    short_name: 'VI',
    long_name: 'U.S. Virgin Islands',
  }, {
    short_name: 'VN',
    long_name: 'Vietnam',
  }, {
    short_name: 'VU',
    long_name: 'Vanuatu',
  }, {
    short_name: 'WF',
    long_name: 'Wallis and Futuna',
  }, {
    short_name: 'WS',
    long_name: 'Samoa',
  }, {
    short_name: 'YE',
    long_name: 'Yemen',
  }, {
    short_name: 'YT',
    long_name: 'Mayotte',
  }, {
    short_name: 'ZA',
    long_name: 'South Africa',
  }, {
    short_name: 'ZM',
    long_name: 'Zambia',
  }, {
    short_name: 'ZW',
    long_name: 'Zimbabwe',
  }, {
    short_name: 'CS',
    long_name: 'Serbia and Montenegro',
  }, {
    short_name: 'AN',
    long_name: 'Netherlands Antilles',
  },
];
